[package]
name = "rust_lifetime_sample"
version = "0.1.0"
authors = ["Isaac Post <post.isaac@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
